#!/usr/bin/Rscript
library(reshape2)
library(ggplot2)
library(grid)
library(gridExtra)
library(plyr)



filenames=list.files(path = "~/Research/RpcTransportDesign/OMNeT++Simulation/analysis/PlotScripts/fileList" ,pattern= '*.txt', full.names = TRUE)

# colorSchema <- ("red", "black", "blue", "green", "yellow")
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
allW <- c('W1', 'W2', 'W3', 'W4', 'W5')
allWorkloads <- c('FACEBOOK_KEY_VALUE', 'GOOGLE_SEARCH_RPC',
       'FABRICATED_HEAVY_MIDDLE', 'GOOGLE_ALL_RPC','FACEBOOK_HADOOP_ALL')

	textSize <- 35 
	titleSize <- 35 
	yLimit <- 15
		yLab = '99% Slowdoan (Log Scale)\n'
		xLab <- 'Message Sizes (Bytes)'

fileLength <-  length(filenames)

index <- 0

# tailStretchPlot = list()
tailStretchPlot <- ggplot()

i <- 0
pdf(sprintf("plotPBS/TailStretchVsUnschedBytes%s.pdf", fileLength), width=40, height=20)
# Plots the stretch vs. unsched bytes from text data files generated by
# PlotDigeter.py script
# print(filenames)
for (filename in filenames){ 
    print(filename)
    stretch <- read.table(filename,
    	na.strings = "NA",
   	 col.names=c('LoadFactor', 'WorkLoad', 'MsgSizeRange',
    	'SizeCntPercent', 'BytesPercent', 'UnschedBytes', 'MeanStretch',
    	'MedianStretch', 'TailStretch'), header=TRUE)
    
    stretch$UnschedBytes <- factor(stretch$UnschedBytes)

     workloads<- allWorkloads[match(unique(stretch$WorkLoad), allWorkloads)]
     levels(stretch$WorkLoad) <- allW[match(levels(stretch$WorkLoad), allWorkloads)]
     stretch$WorkLoad <- as.character(stretch$WorkLoad)
     stretch <- stretch[with(stretch, order(WorkLoad)),]
     stretch$WorkLoad <- as.factor(stretch$WorkLoad)
     Ws <- levels(stretch$WorkLoad)

     stretch$LoadFactor <- factor(stretch$LoadFactor)

     tailStretch <- subset(stretch,
	    !is.na(TailStretch) & !(MsgSizeRange %in% c('Huge', 'OverAllSizes')),
	    select=c( 'LoadFactor', 'WorkLoad', 'MsgSizeRange',
	    'SizeCntPercent', 'BytesPercent', 'UnschedBytes', 'TailStretch'))

	tailStretch <- ddply(tailStretch,
	    .(LoadFactor, WorkLoad, UnschedBytes), transform,
	    SizeCumPercent = round(cumsum(SizeCntPercent), 2),
	    BytesCumPercent = round(cumsum(BytesPercent), 2))

	tailStretch$MsgSizeRange <- as.numeric(
	    as.character(tailStretch$MsgSizeRange))

	for (rho in unique(tailStretch$LoadFactor)) {
	    for (workload in Ws) {
		# Use CDF as the x axis
		tmp <- subset(tailStretch, WorkLoad==workload & LoadFactor==rho,
		    select=c('LoadFactor', 'WorkLoad', 'MsgSizeRange', 'SizeCntPercent',
		    'SizeCumPercent', 'TailStretch', 'UnschedBytes'))
		if (nrow(tmp) == 0) {
		    next
		}

		i <- i+1
		plotTitle = sprintf("Workload: %s                                 ",
		    workload)


		# You might ask why I'm using "x=SizeCumPercent-SizeCntPercent/200" in
		# the plot? The reason is that ggplot geom_bar is so dumb and I was
		# not able to shift the bars to the write while setting the width of
		# each bar to be equal to it's size probability. So I ended up manaully
		# shift the bars to the the left for half of the probability and
		# setting the width equal to the probability
		tailStretchPlot <-  tailStretchPlot + geom_step(data=tmp, aes(x=SizeCumPercent-SizeCntPercent/2,
		    y=TailStretch, width=SizeCntPercent, colour=UnschedBytes), size=4)

	    }
	}		
    print("finish one file")
}
		plotTitle <- paste(append(unlist(strsplit(plotTitle, split='')), '\n',
		    as.integer(nchar(plotTitle)/2)), sep='', collapse='')

		xIntervals <- findInterval(c(0)+seq(2,102,10),
		    tmp[tmp$UnschedBytes=='9328',]$SizeCumPercent)

		 tailStretchPlot  <-  tailStretchPlot +
		    theme(text = element_text(size=1.5*textSize),
			axis.text = element_text(size=1.3*textSize),
			axis.text.x = element_text(angle=75, vjust=0.5),
			strip.text = element_text(size = textSize),
			plot.title = element_text(size = 1.2*titleSize,color='darkblue', hjust = 0.5), 
			plot.margin=unit(c(2,2,2.5,2.2),"cm"), 
			legend.position = "none") +
			# legend.title = element_blank()) +
			# legend.position = c(0.1, 0.85),
			# legend.text = element_text(size=1.5*textSize)) +
		    guides(colour = guide_legend(override.aes = list(size=textSize/4)))+
		    scale_x_continuous(limits = c(0,101),
			breaks = tmp[xIntervals,]$SizeCumPercent,
			labels=tmp[xIntervals,]$MsgSizeRange, expand = c(0, 0)) +
		    scale_y_log10(breaks=c(1,2,3,4,5,10,15)) +
		    coord_cartesian(ylim=c(1, yLimit)) +
		    labs(title = plotTitle, y = yLab, x = xLab)
args.list <- c(tailStretchPlot, list(ncol=1)
do.call(grid.arrange, args.list)
dev.off()
