# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('homa', ['core', 'network'])
    module.source = [
        'model/homa.cc',
        'helper/homa-helper.cc',
	'model/homaPrioTag.cc',
	'model/homaFlowIdTag.cc',
	'model/homaGrantTag.cc',
        ]

    module_test = bld.create_ns3_module_test_library('homa')
    module_test.source = [
        'test/homa-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'homa'
    headers.source = [
        'model/homa.h',
        'helper/homa-helper.h',
	'model/homaPrioTag.h',
	'model/homaFlowIdTag.h',
	'model/homaGrantTag.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

